CadastroSim/Models/DbCadastro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
namespace CadastroSim.Models
{
    [Table("cadastro", Schema = "public")]
    public class DbCadastro
    {
        [Key]

        public int id { get; set; }
        public string? nome { get; set; }
        public string? email { get; set; }
        public DateTime datanascimento { get; set; }
        public string? sexo { get; set; }
        public string? rua { get; set; }
        public string? numero { get; set; }
        public string? cep { get; set; }
        public string? cidade { get; set; }
        public string? estado { get; set; }
        public string? mensagem { get; set; }

    }
}

CadastroSim/Models/DbContext.cs
using Microsoft.EntityFrameworkCore;
namespace CadastroSim.Models
{
    public class Context : DbContext
    {
        public Context(DbContextOptions<Context> opcoes) : base(opcoes)
        {

        }

        public DbSet<DbCadastro> cadastro { get; set; }
    }
}

CadastroSim/Models/ErrorViewModel.cs
namespace CadastroSim.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroSim/Controllers/CadastroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CadastroSim.Models;

namespace CadastroSim.Controllers
{
    public class CadastroesController : Controller
    {
        private readonly Context _context;

        public CadastroesController(Context context)
        {
            _context = context;
        }

        // GET: Cadastroes
        public async Task<IActionResult> Index()
        {
              return _context.cadastro != null ? 
                          View(await _context.cadastro.ToListAsync()) :
                          Problem("Entity set 'Context.cadastro'  is null.");
        }

        // GET: Cadastroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.cadastro == null)
            {
                return NotFound();
            }

            var dbCadastro = await _context.cadastro
                .FirstOrDefaultAsync(m => m.id == id);
            if (dbCadastro == null)
            {
                return NotFound();
            }

            return View(dbCadastro);
        }

        // GET: Cadastroes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cadastroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome,email,datanascimento,sexo,rua,numero,cep,cidade,estado,mensagem")] DbCadastro dbCadastro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dbCadastro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dbCadastro);
        }

        // GET: Cadastroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.cadastro == null)
            {
                return NotFound();
            }

            var dbCadastro = await _context.cadastro.FindAsync(id);
            if (dbCadastro == null)
            {
                return NotFound();
            }
            return View(dbCadastro);
        }

        // POST: Cadastroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome,email,datanascimento,sexo,rua,numero,cep,cidade,estado,mensagem")] DbCadastro dbCadastro)
        {
            if (id != dbCadastro.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dbCadastro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DbCadastroExists(dbCadastro.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dbCadastro);
        }

        // GET: Cadastroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.cadastro == null)
            {
                return NotFound();
            }

            var dbCadastro = await _context.cadastro
                .FirstOrDefaultAsync(m => m.id == id);
            if (dbCadastro == null)
            {
                return NotFound();
            }

            return View(dbCadastro);
        }

        // POST: Cadastroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.cadastro == null)
            {
                return Problem("Entity set 'Context.cadastro'  is null.");
            }
            var dbCadastro = await _context.cadastro.FindAsync(id);
            if (dbCadastro != null)
            {
                _context.cadastro.Remove(dbCadastro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DbCadastroExists(int id)
        {
          return (_context.cadastro?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

CadastroSim/Controllers/HomeController.cs
using CadastroSim.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroSim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroSim/Views/Cadastroes/Create.cshtml
@model CadastroSim.Models.DbCadastro

@{
    ViewData["Title"] = "Criar Novo";
}

<h1>Criar Novo</h1>

<h4>Novo Cadastro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Nome</label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">E-mail</label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data Nascimento</label>
                <input asp-for="datanascimento" class="form-control" />
                <span asp-validation-for="datanascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Sexo</label>
                <input asp-for="sexo" class="form-control" />
                <span asp-validation-for="sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rua</label>
                <input asp-for="rua" class="form-control" />
                <span asp-validation-for="rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Número</label>
                <input asp-for="numero" class="form-control" />
                <span asp-validation-for="numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">CEP</label>
                <input asp-for="cep" class="form-control" />
                <span asp-validation-for="cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Cidade</label>
                <input asp-for="cidade" class="form-control" />
                <span asp-validation-for="cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Estado</label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mensagem</label>
                <input asp-for="mensagem" class="form-control" />
                <span asp-validation-for="mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar Cadastro" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroSim/Views/Cadastroes/Delete.cshtml
@model CadastroSim.Models.DbCadastro

@{
    ViewData["Title"] = "Deletar";
}

<h1>Deletar Cadastro</h1>

<h3>Você tem certeza que quer deletar este Cadastro?</h3>
<div>
    <h4>Deletar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nome
            @*@Html.DisplayNameFor(model => model.nome)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            E-mail
            @*@Html.DisplayNameFor(model => model.email)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            Data Nascimento
            @*@Html.DisplayNameFor(model => model.datanascimento)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.datanascimento)
        </dd>
        <dt class = "col-sm-2">
            Sexo
            @*@Html.DisplayNameFor(model => model.sexo)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sexo)
        </dd>
        <dt class = "col-sm-2">
            Rua
            @*@Html.DisplayNameFor(model => model.rua)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rua)
        </dd>
        <dt class = "col-sm-2">
            Número
            @*@Html.DisplayNameFor(model => model.numero)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numero)
        </dd>
        <dt class = "col-sm-2">
            CEP
            @*@Html.DisplayNameFor(model => model.cep)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cep)
        </dd>
        <dt class = "col-sm-2">
            Cidade
            @*@Html.DisplayNameFor(model => model.cidade)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cidade)
        </dd>
        <dt class = "col-sm-2">
            Estado
            @*@Html.DisplayNameFor(model => model.estado)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
        <dt class = "col-sm-2">
            Mensagem
            @*@Html.DisplayNameFor(model => model.mensagem)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mensagem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

CadastroSim/Views/Cadastroes/Details.cshtml
@model CadastroSim.Models.DbCadastro

@{
    ViewData["Title"] = "Detalhes Cadastro";
}

<h1>Detalhes do Cadastro</h1>

<div>
    <h4>Detalhes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nome
            @*@Html.DisplayNameFor(model => model.nome)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            E-mail
            @*@Html.DisplayNameFor(model => model.email)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            Data Nascimento
            @*@Html.DisplayNameFor(model => model.datanascimento)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.datanascimento)
        </dd>
        <dt class = "col-sm-2">
            Sexo
            @*@Html.DisplayNameFor(model => model.sexo)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sexo)
        </dd>
        <dt class = "col-sm-2">
            Rua
            @*@Html.DisplayNameFor(model => model.rua)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rua)
        </dd>
        <dt class = "col-sm-2">
            Número
            @*@Html.DisplayNameFor(model => model.numero)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numero)
        </dd>
        <dt class = "col-sm-2">
            CEP
            @*@Html.DisplayNameFor(model => model.cep)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cep)
        </dd>
        <dt class = "col-sm-2">
            Cidade
            @*@Html.DisplayNameFor(model => model.cidade)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cidade)
        </dd>
        <dt class = "col-sm-2">
            Estado
            @*@Html.DisplayNameFor(model => model.estado)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
        <dt class = "col-sm-2">
            Mensagem
            @*@Html.DisplayNameFor(model => model.mensagem)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mensagem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>

CadastroSim/Views/Cadastroes/Edit.cshtml
@model CadastroSim.Models.DbCadastro

@{
    ViewData["Title"] = "Editar Cadastro";
}

<h1>Editar Cadastro</h1>

<h4>Editar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label class="control-label">Nome</label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">E-mail</label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Data Nascimento</label>
                <input asp-for="datanascimento" class="form-control" />
                <span asp-validation-for="datanascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Sexo</label>
                <input asp-for="sexo" class="form-control" />
                <span asp-validation-for="sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rua</label>
                <input asp-for="rua" class="form-control" />
                <span asp-validation-for="rua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Número</label>
                <input asp-for="numero" class="form-control" />
                <span asp-validation-for="numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">CEP</label>
                <input asp-for="cep" class="form-control" />
                <span asp-validation-for="cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Cidade</label>
                <input asp-for="cidade" class="form-control" />
                <span asp-validation-for="cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Estado</label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mensagem</label>
                <input asp-for="mensagem" class="form-control" />
                <span asp-validation-for="mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroSim/Views/Cadastroes/Index.cshtml
@model IEnumerable<CadastroSim.Models.DbCadastro>

@{
    ViewData["Title"] = "Cadastro";
}

<h1>Cadastros</h1>

<p>
    <a asp-action="Create">Criar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
                @*@Html.DisplayNameFor(model => model.nome)*@
            </th>
            <th>
                E-mail
                @*@Html.DisplayNameFor(model => model.email)*@
            </th>
            <th>
                Data Nascimento
                @*@Html.DisplayNameFor(model => model.datanascimento)*@
            </th>
            <th>
                Sexo
                @*@Html.DisplayNameFor(model => model.sexo)*@
            </th>
            <th>
                Rua
                @*@Html.DisplayNameFor(model => model.rua)*@
            </th>
            <th>
                Número
                @*@Html.DisplayNameFor(model => model.numero)*@
            </th>
            <th>
                CEP
                @*@Html.DisplayNameFor(model => model.cep)*@
            </th>
            <th>
                Cidade
                @*@Html.DisplayNameFor(model => model.cidade)*@
            </th>
            <th>
                Estado
                @*@Html.DisplayNameFor(model => model.estado)*@
            </th>
            <th>
                Mensagem
                @*@Html.DisplayNameFor(model => model.mensagem)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.datanascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rua)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mensagem)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

CadastroSim/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!!</h1>
    <p>Sistema de Cadastro Simples</p>
</div>

<body class="text-center">
        
    <img height="650" width="1300" src="https://img.olhardigital.com.br/wp-content/uploads/2019/10/20191009103641-988x450.jpg"

</body>

CadastroSim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro Simples</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroSim.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro Simples</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastroes" asp-action="Index">Cadastro</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Direitos reservados. &copy; 2022 - Cadastro Simples - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>